let questions = [
    // Musterprüfung 1 Beginn
    {
        "question": "1) Welche Practice ist für die Bereitstellung von Komponenten in Live-Umgebungen verantwortlich?",
        "answer_1": "A. Change Control",
        "answer_2": "B. Release Management",
        "answer_3": "C. IT Asset Management",
        "answer_4": "D. Deployment Management",
        "right_answer": 4,
    },
    {
        "question": "2) Welche Practice umfasst die Klassifizierung und Verantwortung für Fragen und Anfragen von Anwendern?",
        "answer_1": "A. Service Desk",
        "answer_2": "B. Incident Management",
        "answer_3": "C. Change Control",
        "answer_4": "D. Service Level Management",
        "right_answer": 1,
    },
    {
        "question": "3) Welche Practice identifiziert Messgrößen, welche die Serviceerfahrung des Kunden widerspiegeln?",
        "answer_1": "A. Continual Improvement",
        "answer_2": "B. Service Desk",
        "answer_3": "C. Service Level Management",
        "answer_4": "D. Problem Management",
        "right_answer": 3,
    },
    {
        "question": "4) Was ist die VORWIEGENDE Verwendung eines Change-Kalenders?",
        "answer_1": "A. Unterstützen des „Incident Management“ und der Verbesserungsplanung",
        "answer_2": "B. Managen von Notfall-Changes",
        "answer_3": "C. Planen von Changes und Beitragen zur Konfliktvermeidung",
        "answer_4": "D. Managen von Standard-Changes",
        "right_answer": 3,
    },
    {
        "question": "5) Welche Dimension des Service Managements konzentriert sich auf Aktivitäten und deren Koordination?",
        "answer_1": "A. Organisationen und Menschen",
        "answer_2": "B. Informationen und Technologie",
        "answer_3": "C. Partner und Lieferanten",
        "answer_4": "D. Wertströme und Prozesse",
        "right_answer": 4,
    },
    {
        "question": "6) Wie unterstützt die Kategorisierung von Incidents die „Incident Management Practice“?",
        "answer_1": "A. Sie erleichtert die Zuweisung des Incidents zum richtigen Supportbereich",
        "answer_2": "B. Sie legt die Priorität fest, die dem Incident zugewiesen wird",
        "answer_3": "C. Sie stellt sicher, dass Incidents innerhalb von Zeitfenstern gelöst werden, die mit dem Kunden vereinbart wurden",
        "answer_4": "D. Sie bestimmt, wie der Service Provider wahrgenommen wird",
        "right_answer": 1,
    },
    {
        "question": "7) Identifizieren Sie das/die fehlende(n) Wort/Wörter im folgenden Satz. Ein Service ist eine Möglichkeit, gemeinsamen Mehrwert zu schaffen, indem das Erreichen der von Kunden angestrebten [?] erleichtert wird.",
        "answer_1": "A. Warranty",
        "answer_2": "B. Ergebnisse",
        "answer_3": "C. Utility",
        "answer_4": "D. Outputs",
        "right_answer": 2,
    },
    {
        "question": "8) Was ist eine Empfehlung der „Continual Improvement Practice“?",
        "answer_1": "A. Zumindest ein kleines Team sollte sich für ein „Continual Improvement“ engagieren.",
        "answer_2": "B. Alle Verbesserungen sollten als mehrphasige Projekte gemanagt werden",
        "answer_3": "C. „Continual Improvement“ sollte von anderen Practices getrennt sein",
        "answer_4": "D. Externe Lieferanten sollten aus Verbesserungsinitiativen ausgeschlossen sein",
        "right_answer": 1,
    },
    {
        "question": "9) Was ist ein möglicher Vorteil der Verwendung eines IT Service Management-Tools zur Unterstützung der „Incident Management Practice“?",
        "answer_1": "A. Es kann sicherstellen, dass die Ursache von Incidents in der vereinbarten Zeit ermittelt wird",
        "answer_2": "B. Es kann einen automatischen Abgleich von Incidents mit Problemen oder Known Errors ermöglichen",
        "answer_3": "C. Es kann sicherstellen, dass Lieferantenverträge auf die Anforderungen des Service Providers abgestimmt sind",
        "answer_4": "D. Es kann die automatisierte Lösung und Schließung komplexer Incidents ermöglichen",
        "right_answer": 2,
    },
    {
        "question": "10) Welche Rolle übermittelt Service Requests?",
        "answer_1": "A. Der Anwender oder dessen autorisierter Vertreter",
        "answer_2": "B. Der Kunde oder dessen autorisierter Vertreter",
        "answer_3": "C. Der Sponsor oder dessen autorisierter Vertreter",
        "answer_4": "D. Der Lieferant oder dessen autorisierter Vertreter",
        "right_answer": 1,
    },
    {
        "question": "11) Welche Practice stellt einen Single Point of Contact für Anwender bereit?",
        "answer_1": "A. Der Incident Management",
        "answer_2": "B. Change Control",
        "answer_3": "C. Service Desk",
        "answer_4": "D. Service Request Management",
        "right_answer": 3,
    },
    {
        "question": "12) Welches Grundprinzip empfiehlt, dass die vier Dimensionen des Service Management berücksichtigt werden?",
        "answer_1": "A. Ganzheitlich denken und arbeiten",
        "answer_2": "B. Iterative Weiterentwicklung mit Feedback",
        "answer_3": "C. Wertorientierung",
        "answer_4": "D. Auf Einfachheit und Praktikabilität achten",
        "right_answer": 1,
    },
    {
        "question": "13) Was würde durch die „Service Request Management Practice“ unterstützt werden?",
        "answer_1": "A. Eine Anfrage zur Autorisierung eines Change, der Auswirkung auf einen Service haben könnte",
        "answer_2": "B. Eine Anfrage eines Anwenders für eine Aktion, die ein normaler Bestandteil der Servicebereitstellung ist",
        "answer_3": "C. Eine Anfrage zur Wiederherstellung eines Service nach einer Serviceunterbrechung",
        "answer_4": "D. Eine Anfrage zur Untersuchung der Ursache mehrerer miteinander verwandter Incidents",
        "right_answer": 2,
    },
    {
        "question": "14) Welche Practice ist die Verantwortlichkeit eines jeden Organisationsmitglieds?",
        "answer_1": "A. Service Level Management",
        "answer_2": "B. Change Control",
        "answer_3": "C. Problem Management",
        "answer_4": "D. Continual Improvement",
        "right_answer": 4,
    },
    {
        "question": "15) Identifizieren Sie das fehlende Wort im folgenden Satz. Der Zweck der „Information Security Management Practice“ ist, die Informationen der Organisation [?] .",
        "answer_1": "A. zu speichern",
        "answer_2": "B. bereitzustellen",
        "answer_3": "C. zu prüfen",
        "answer_4": "D. zu schützen",
        "right_answer": 4,
    },
    {
        "question": "16) Welches Grundprinzip empfiehlt, vor der Entscheidung darüber, was erneut verwendet werden kann, zunächst Daten zu sammeln?",
        "answer_1": "A. Wertorientierung",
        "answer_2": "B. Dort beginnen, wo man steht",
        "answer_3": "C. Auf Einfachheit und Praktikabilität achten",
        "answer_4": "D. Iterative Weiterentwicklung mit Feedback",
        "right_answer": 2,
    },
    {
        "question": "17) Was ist normalerweise NICHT im Incident Management enthalten?",
        "answer_1": "A. Skripte zur Sammlung erster Informationen zu Incidents",
        "answer_2": "B. Formalisierte Verfahren zur Erfassung von Incidents",
        "answer_3": "C. Detaillierte Verfahren für die Diagnose von Incidents",
        "answer_4": "D. Die Nutzung von Spezialwissen für komplizierte Incidents",
        "right_answer": 3,
    },
    {
        "question": "18) Welche Aussage beschreibt das Wesen der Grundprinzipien?",
        "answer_1": "A. Grundprinzipien können eine Organisation in allen Situationen leiten",
        "answer_2": "B. Jedes Grundprinzip fordert spezifische Aktionen und Entscheidungen",
        "answer_3": "C. Eine Organisation wählt und übernimmt nur eines der sieben Grundprinzipien",
        "answer_4": "D. Grundprinzipien beschreiben die Prozesse, die alle Organisationen übernehmen müssen",
        "right_answer": 1,
    },
    {
        "question": "19) Welche Aussage über eine Change-Autorität ist RICHTIG?",
        "answer_1": "A. Eine einzelne Change-Autorität sollte zugewiesen werden, um alle Arten von Changes und Change-Modellen zu autorisieren",
        "answer_2": "B. Eine Change-Autorität sollte für jede Art von Change und Change-Modell zugewiesen werden",
        "answer_3": "C. Normale Changes sind vorab autorisiert und erfordern keine Change-Autorität",
        "answer_4": "D. Notfall-Changes können ohne Autorisierung von einer Change-Autorität implementiert werden",
        "right_answer": 2,
    },
    {
        "question": "20) Welche Practice verfolgt den Zweck, neue und geänderte Services und Funktionen zur Verfügung zu stellen?",
        "answer_1": "A. Change Control",
        "answer_2": "B. Service Request Management",
        "answer_3": "C. Release Management",
        "answer_4": "D. Deployment Management",
        "right_answer": 3,
    },
    {
        "question": "21) Welche Wertschöpfungskettenaktivität stellt sicher, dass Beteiligte die Vision der Organisation verstehen?",
        "answer_1": "A. Verbesserung",
        "answer_2": "B. Planung",
        "answer_3": "C. Bereitstellung und Support",
        "answer_4": "D. Erhalten/Erstellen",
        "right_answer": 2,
    },
    {
        "question": "22) Welche Aussage zu den Aktivitäten der Wertschöpfungskette ist RICHTIG?",
        "answer_1": "A. Jede Practice gehört zu einer bestimmten Aktivität der Wertschöpfungskette",
        "answer_2": "B. Eine bestimmte Kombination von Aktivitäten der Wertschöpfungskette und Practices bildet eine Servicebeziehung",
        "answer_3": "C. Aktivitäten der Wertschöpfungskette bilden einen einzelnen Workflow, der Wertschöpfung ermöglicht",
        "answer_4": "D. Jede Aktivität der Wertschöpfungskette trägt zur Wertschöpfungskette bei, indem sie bestimmte Inputs in Outputs umwandelt",
        "right_answer": 4,
    },
    {
        "question": "23) Welchen Zweck verfolgt die „Supplier Management Practice“?",
        "answer_1": "A. Sicherstellen, dass die Lieferanten der Organisation und ihre Leistung angemessen gemanagt werden, um die nahtlose Bereitstellung von Qualitätsprodukten und -services zu unterstützen",
        "answer_2": "B. Anpassen der Practices und Services der Organisation an sich ändernde Geschäftsanforderungen durch die kontinuierliche Identifizierung und Verbesserung von Services",
        "answer_3": "C. Sicherstellen, dass die Lieferanten der Organisation und ihre Performances auf strategischer und taktischer Ebene durch koordinierte Marketing-, Verkaufs- und Bereitstellungsaktivitäten angemessen gemanagt werden",
        "answer_4": "D. Sicherstellen, dass jederzeit und überall genaue und zuverlässige Informationen über die Konfiguration von Services der Lieferanten verfügbar sind",
        "right_answer": 1,
    },
    {
        "question": "24) Welches sind die zwei Arten von Kosten, die ein Servicekonsument beurteilen sollte?",
        "answer_1": "A. Der Preis des Service und die Kosten der Erstellung des Service",
        "answer_2": "B. Die Kosten, die durch den Service entfallen, und die Kosten, die durch den Service auferlegt werden",
        "answer_3": "C. Die Kosten der Bereitstellung des Service und die Kosten der Verbesserung des Service",
        "answer_4": "D. Die Kosten der Software und die Kosten der Hardware",
        "right_answer": 2,
    },

    {
        "question": "25) Welchen Zweck verfolgt die „Service Desk Practice“?",
        "answer_1": "A. Reduzieren der Wahrscheinlichkeit und der Auswirkung von Incidents durch Identifizierung tatsächlicher und potenzieller Ursachen von Incidents",
        "answer_2": "B. Maximieren der Anzahl erfolgreicher IT-Changes indem sichergestellt wird, dass Risiken richtig bewertet werden",
        "answer_3": "C. Erfassen der Nachfrage nach der Lösung von Incidents und Service Requests (Serviceanfragen)",
        "answer_4": "D. Festlegen klarer, geschäftsbasierter Ziele für die Serviceleistung",
        "right_answer": 3,
    },
    {
        "question": "26) Wie sollte eine Organisation Methoden der ständigen Verbesserung übernehmen?",
        "answer_1": "A. Für jede von der Organisation implementierte Verbesserung eine neue Methode verwenden",
        "answer_2": "B. Für die Arten von Verbesserung, welche die Organisation umsetzt, einige Schlüsselmethoden auswählen",
        "answer_3": "C. Die Fähigkeit aufbauen, so viele Verbesserungsmethoden wie möglich zu verwenden",
        "answer_4": "D. Für alle Verbesserungen, welche die Organisation implementiert, jeweils eine einzelne Methode auswählen",
        "right_answer": 2,
    },
    {
        "question": "27) Welches ITIL-Konzept beschreibt Governance?",
        "answer_1": "A. Die sieben Grundprinzipien",
        "answer_2": "B. Die vier Dimensionen des Service Management",
        "answer_3": "C. Die Service-Wertschöpfungskette",
        "answer_4": "D. Das Servicewertsystem",
        "right_answer": 4,
    },
    {
        "question": "28) Was ist eine Empfehlung der „Service Desk Practice“?",
        "answer_1": "A. Service Desks sollten den Einsatz von Automatisierung vermeiden",
        "answer_2": "B. Service Desks sollten stark spezialisiert sein",
        "answer_3": "C. Service Desks sollten die Organisation als Ganzes verstehen",
        "answer_4": "D. Service Desks sollten ein physisches Team an einem einzelnen festen Standort sein",
        "right_answer": 3,
    },
    {
        "question": "29) Welches Grundprinzip empfiehlt, Aufgaben in kleinere, handlichere Schritte zu unterteilen, die in einem übersichtlichen Zeitrahmen ausgeführt und abgeschlossen werden können?",
        "answer_1": "A. Wertorientierung",
        "answer_2": "B. Dort beginnen, wo man steht",
        "answer_3": "C. Iterative Weiterentwicklung mit Feedback",
        "answer_4": "D. Zusammenarbeiten und Transparenz fördern",
        "right_answer": 3,
    },
    {
        "question": "30) Was ist ein Standard-Change?",
        "answer_1": "A. Ein Change, der wohlverstanden, umfassend dokumentiert und vorab autorisiert ist",
        "answer_2": "B. Ein Change, der von einer Change-Autorität bewertet, autorisiert und geplant werden muss",
        "answer_3": "C. Ein Change, für den eine Risikobewertung erforderlich ist, weil er zur Lösung eines Incidents erforderlich ist",
        "answer_4": "D. Ein Change, der im Rahmen von „Continual Improvement“ bewertet, autorisiert und geplant wird",
        "right_answer": 1,
    },
    {
        "question": "31) Was passiert, wenn ein Workaround (Umgehungslösung) zur dauerhaften Lösung für ein Problem wird, das nicht kosteneffektiv gelöst werden kann?",
        "answer_1": "A. Ein Change-Request wird an die Change Control gesendet",
        "answer_2": "B. Das Problem Management stellt den Service so bald wie möglich wieder her",
        "answer_3": "C. Das Problem verbleibt im Status „Known Error“",
        "answer_4": "D. Der Problem Record wird gelöscht",
        "right_answer": 3,
    },
    {
        "question": "32) Wie lautet die Definition von Change?",
        "answer_1": "A. Hinzufügen, Modifizieren oder Entfernen eines Elements, das direkte oder indirekte Auswirkungen auf Services haben könnte",
        "answer_2": "B. Sicherstellen, dass genaue und zuverlässige Informationen über die Konfiguration von Services verfügbar sind",
        "answer_3": "C. Zurverfügungstellen neuer und geänderter Services und Funktionen",
        "answer_4": "D. Bereitstellen neuer oder geänderter Hardware, Software oder anderer Servicekomponenten in Live-Umgebungen",
        "right_answer": 1,
    },
    {
        "question": "33) Wie lautet die Definition eines Event?",
        "answer_1": "A. Jede Statusänderung, die für das Management eines Service oder eines anderen Configuration Item (CI) von Bedeutung ist",
        "answer_2": "B. Alle Komponenten, die gemanagt werden müssen, um einen IT Service bereitstellen zu können",
        "answer_3": "C. Eine nicht geplante Unterbrechung eines Service oder eine Qualitätsminderung eines Service",
        "answer_4": "D. Jede finanziell wertvolle Komponente, die zur Bereitstellung eines IT-Produkts oder Erbringung eines IT Service beitragen kann",
        "right_answer": 1,
    },
    {
        "question": "34) Welche Aussage beschreibt Ergebnisse?",
        "answer_1": "A. Materielle oder immaterielle Liefergegenstände",
        "answer_2": "B. Funktionalität, die von einem Produkt oder Service angeboten wird",
        "answer_3": "C. Von einem Stakeholder gewünschte Ergebnisse",
        "answer_4": "D. Konfiguration der Ressourcen einer Organisation",
        "right_answer": 3,
    },
    {
        "question": "35) Was ist KEIN zentraler Fokus der Dimension „Informationen und Technologie“?",
        "answer_1": "A. Security und Compliance",
        "answer_2": "B. Kommunikationssysteme und Wissensdatenbanken",
        "answer_3": "C. Workflow-Management und Bestandssysteme",
        "answer_4": "D. Rollen und Verantwortlichkeiten",
        "right_answer": 4,
    },
    {
        "question": "36) Welche Practices sind normalerweise an der Implementierung einer Problemlösung beteiligt?",
        "answer_1": "A.Continual Improvement ",
        "answer_2": "B. Service Request Management",
        "answer_3": "C. Service Level Management",
        "answer_4": "D. Change Control",
        "right_answer": 4,
    },
    {
        "question": "37) Was ist eine zentrale Überlegung des Grundprinzips „Auf Einfachheit und Praktikabilität achten“?",
        "answer_1": "A. Versuchen, eine Lösung für jede Ausnahme zu erstellen",
        "answer_2": "B. Verstehen, wie jedes Element zur Wertschöpfung beiträgt",
        "answer_3": "C. Die widerstreitenden Zielsetzungen verschiedener Stakeholder ignorieren",
        "answer_4": "D. Mit einer komplexen Lösung beginnen, dann vereinfachen",
        "right_answer": 2,
    },
    {
        "question": "38) Was sollte zuerst getan werden, wenn das Grundprinzip „Wertorientierung“ angewendet wird?",
        "answer_1": "A. Die Ergebnisse identifizieren, die der Service unterstützt",
        "answer_2": "B. Alle am Service beteiligten Lieferanten und Partner identifizieren",
        "answer_3": "C. Sich in jeder Situation bewusst sein, wer der Servicekonsument ist",
        "answer_4": "D. Die Kosten für die Bereitstellung des Service ermitteln",
        "right_answer": 3,
    },
    {
        "question": "39) Ein Service Provider beschreibt ein Paket, das einen Laptop mit Software, Lizenzen und Support umfasst. Wofür ist dieses Paket ein Beispiel?",
        "answer_1": "A. Wert",
        "answer_2": "B. Ein Ergebnis",
        "answer_3": "C. Warranty",
        "answer_4": "D. Ein Serviceangebot",
        "right_answer": 4,
    },
    {
        "question": "40) Wie lautet die Definition von Warranty?",
        "answer_1": "A. Ein materieller oder immaterieller Liefergegenstand, der durch die Ausführung einer Aktivität geschaffen wird",
        "answer_2": "B. Die Zusicherung, dass ein Produkt oder Service den vereinbarten Anforderungen entspricht",
        "answer_3": "C. Ein mögliches Event, das zu einem Schaden oder Verlust führen oder das Erreichen von Zielen erschweren könnte",
        "answer_4": "D. Die Funktionalität, die von einem Produkt oder Service angeboten wird, um einem bestimmten Bedürfnis gerecht zu werden",
        "right_answer": 2,
    },

    // Musterprüfung 1 End
]
/*
{
    "question": ") ",
    "answer_1": "A. ",
    "answer_2": "B. ",
    "answer_3": "C. ",
    "answer_4": "D. ",
    "right_answer": ,
},
*/